### ISSUE TITLE
Segmentation Fault Core Dumped

### ISSUE THREAD

**Issue by Nakul1048** [CMU-SAFARI/DRAM-Bender#4]
Hello, after following your tutorial on youtube from the video 
0:00 / 43:14
P&S DRAM Bender: DRAM Bender Tutorial (Fall 2022) 

We are running into an issue where when we run the code for main.cpp we get a Open to card failed! error along with a Segmentation Fault (core dumped)

Downloads/DRAM-Bender-master$ ls 
images  LICENSE  prebuilt  projects  README.md  sources
Downloads/DRAM-Bender-master$ cd sources/
Downloads/DRAM-Bender-master/sources$ cd apps/
Downloads/DRAM-Bender-master/sources/apps$ ls 
DebugExample  parsertest  QUAC-TRNG  ResetBoard  RetentionTest  RowHammerExample  SanityCheck  Smalltest
Downloads/DRAM-Bender-master/sources/apps$ cd RowHammerExample/
Downloads/DRAM-Bender-master/sources/apps/RowHammerExample$ ls
main.cpp  main.o  Makefile  ps
Downloads/DRAM-Bender-master/sources/apps/RowHammerExample$ ./ps 10
Open to card failed!
Segmentation fault (core dumped)
Downloads/DRAM-Bender-master/sources/apps/RowHammerExample$

**Comment by olgunataberk** [comment]
The DRAM Bender API likely cannot open XDMA file(s) under `/dev` because the API does not have read permissions for the XDMA files.

I suggest you try with sudo (i.e., `sudo ./ps 10`) unless you are using a different OS/driver configuration than what we have tested.
