### ISSUE TITLE
Xilinx ZC706 Board support

### ISSUE THREAD

**Issue by robotic9877** [CMU-SAFARI/DRAM-Bender#9]
Hello,

I read your paper "DRAM Bender: An Extensible and Versatile FPGA-based Infrastructure to Easily Test State-of-the-art DRAM Chips" and your group mentioned that DRAM bender could support the ZC706 board. Could you publish the board files? Thanks.

**Comment by olgunataberk** [comment]
You can find them here https://github.com/CMU-SAFARI/DRAM-Bender/tree/zc706

**Comment by robotic9877** [comment]
Thank you for the help. Is there a guide already on the master that I can follow for the zc706? For example, follow the guide for the XUSP3S, but change the PCIe driver install step to use the zc706 driver.
